import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="mn">
      <body>
        <div className="flex">
          <div className="flex-1 flex flex-col">
            <Navbar/>
            <main className="">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
